project:
  type: book

book:
  title: "County Business Patterns in North Carolina 2001-2021"
  author: "Daniel Moul"
  date: today
  chapters:
    - index.qmd
    - cbd-employment-wages.qmd
    - cbd-establishments.qmd
    - observations-sectors.qmd
    - notes.qmd

execute:
  #cache: true
  freeze: auto  # re-render only when source changes
#  echo: false
  
#bibliography: references.bib

format:
  html:
    theme: cosmo
    code-fold: true
    code-summary: "Show the code"
#  pdf:
#    documentclass: scrreprt



