project:
  type: book

book:
  title: "County Business Patterns in North Carolina 2001-2021"
  author: "Daniel Moul"
  date: "July 10, 2023"
  cover-image: "./images/800px-Entering_Union_County_on_North_Carolina_Highway_200.jpg"
  cover-image-alt: "Weclome to North Carolina highway sign"
  chapters:
    - index.qmd
    - cbp-employment-wages.qmd
    - cbp-establishments.qmd
    - observations-sectors.qmd
    - notes.qmd

#execute:
#  freeze: auto  # re-render only when source changes
  
format:
  html:
    theme: cosmo
    code-fold: true
    code-summary: "Show the code"
